experiment_name: 'car_eval'
dataset: 'shapenet'
checkpoint_path: 'models/car/checkpoints/model_epoch_0060.pth'
root_dir: /home/isleri/shared/test_data/shapenet_car_test/
gt_dir: /home/isleri/haeni001/data/dif/car
split_file: split/car.json
camera_file: shapenet_car_equi_pose.npy 
logging_root: ./logs

batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
hidden_num: 128
latent_dim: 128
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 3000
on_surface_points: 4000
steps_til_summary: 100
