experiment_name: 'chair_pascal3d_sym_eval'
checkpoint_path: 'models/chair/checkpoints/model_epoch_0060.pth'
root_dir: /home/isleri/shared/test_data/pascal3d_chair/
gt_dir: /home/isleri/shared/test_data/pascal3d_chair/pascal3d_imagenet_chair_val.h5
camera_file: pascal3d_chair_equi_pose.npy
logging_root: ./logs

batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
hidden_num: 128
latent_dim: 128
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 4000
on_surface_points: 4000
steps_til_summary: 100
