experiment_name: 'plane_partial_symmetry'
checkpoint_path: 'models/plane/checkpoints/model_epoch_0060.pth'
root_dir: /home/isleri/haeni001/data/dif/plane/
split_file: split/plane.json
logging_root: ./logs

batch_size: 1
epochs: 30
epochs_til_checkpoint: 5
hidden_num: 128
latent_dim: 128
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 3500
on_surface_points: 4000
steps_til_summary: 100
