root_dir: /home/isleri/haeni001/data/dif/
split_file: split/car.json
logging_root: ./logs
experiment_name: car_depth

batch_size: 256
epochs: 300
lr: 0.0001
num_instances: 3000
epochs_til_checkpoint: 10
steps_til_summary: 100
