root_dir: /home/isleri/haeni001/data/dif/
split_file: split/chair.json
logging_root: ./logs
experiment_name: chair_depth

batch_size: 256
epochs: 70
lr: 0.0001
num_instances: 4000
epochs_til_checkpoint: 5
steps_til_summary: 100
