root_dir: ./example_dir
split_file: split/plane.json
logging_root: ./logs
experiment_name: plane_depth

batch_size: 128
epochs: 500
lr: 0.001
num_instances: 3500
epochs_til_checkpoint: 100
steps_til_summary: 100
