experiment_name: 'mug'
checkpoint_path: 'logs/mug/checkpoints/model_final.pth'
root_dir: /home/isleri/haeni001/data/dif/
split_file: split/mug.json

num_instances: 214
latent_dim: 128
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256
