experiment_name: 'table'
checkpoint_path: 'models/table/checkpoints/model_epoch_0060.pth'
root_dir: /home/isleri/haeni001/data/dif/
split_file: split/table.json

num_instances: 4000
latent_dim: 128
model_type: 'sine'
hidden_num: 128
hyper_hidden_layers: 1
hyper_hidden_features: 256
