root_dir: /home/isleri/haeni001/data/dif/
split_file: split/mug.json
logging_root: ./logs
experiment_name: mug 

batch_size: 128
epochs: 100
epochs_til_checkpoint: 10
expand: -1
hidden_num: 128
latent_dim: 128
loss_correct: 100.0
loss_grad_deform: 5
loss_grad_temp: 100.0
lr: 0.0001
max_points: 200000
model_type: sine
num_instances: 641
on_surface_points: 4000
steps_til_summary: 100
